import Head from 'next/head'
import { Provider } from 'react-redux'
import Box from '@mui/material/Box'

import { store } from '../redux/store'
import { Topbar } from 'shared/components'

export default function Home() {
  return (
    <Provider store={store}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box sx={{ flexGrow: 1 }}>
        <Topbar />
      </Box>
    </Provider>
  )
}
